### ISSUE TITLE
v10.0.1 : TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by neilime** [ngx-translate/core#824]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
It seems I'm not the only one : https://www.reddit.com/r/Angular2/comments/88rf25/angular_translations/

Error : 
```
AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Object(...) is not a function
    at TranslateFakeLoader.getTranslation (ngx-translate-core.js:23)
    at TranslateService.getTranslation (ngx-translate-core.js:556)
    at TranslateService.retrieveTranslations (ngx-translate-core.js:543)
    at TranslateService.setDefaultLang (ngx-translate-core.js:483)
    at new AppComponent (app.component.ts:43)
    at createClass (core.js:10382)
    at createDirectiveInstance (core.js:10217)
    at createViewNodes (core.js:11674)
    at createRootView (core.js:11563)
    at callWithDebugContext (core.js:12929)
```
**Expected/desired behavior**

Works fine with previous version 9.1.1

**Reproduction of the problem**

app.components.ts :
```
  constructor(private translateService: TranslateService,) {
    this.translateService.setDefaultLang('fr');
```

**Please tell us about your environment:**

* **ngx-translate version:**  10.0.1

* **Angular version:** 5.2.9
 
* **Browser:** [all]

**Comment by ocombe** [comment]
As answered in like 5 or 6 other similar issues, and explained in the readme and the changelog: V10 is not compatible with Angular 5, only 6+.

**Comment by FriOne** [comment]
For those who need the old version you need `npm i @ngx-translate/core@9.1.1`.
There is example [here](https://github.com/ngx-translate/ionic-example/blob/master/package.json).

**Comment by lut2410** [comment]
![image](https://user-images.githubusercontent.com/26674804/39008651-7fbd1c40-4433-11e8-8639-3c1506442306.png)

**Comment by lut2410** [comment]
![image](https://user-images.githubusercontent.com/26674804/39008746-c135337e-4433-11e8-8f8b-a6394086da93.png)
[https://github.com/ngx-translate/core](url)

**Comment by kumaresanperumal5666** [comment]
I had been struggling with the issues for two days. after taking a look at it. it worked for me. thx

**Comment by aleixsuau** [comment]
If you are using http-loader, the compatible version is 2.0.1: 
npm install @ngx-translate/http-loader@2.0.1 --save

**Comment by ashrafali-v** [comment]
run  npm i @ngx-translate/core@9.1.1 on command prompt working fine for me.

**Comment by lfxsantos** [comment]
> For those who need the old version you need `npm i @ngx-translate/core@9.1.1`.
> There is example [here](https://github.com/ngx-translate/ionic-example/blob/master/package.json).

Thanks!!!!

**Comment by GuoYi1992** [comment]
to use 9.1.1 version worked for me,thank u!!!

**Comment by kapilSoni101** [comment]
#FriOne sir,i have already installed this plugin but again got same error Object(...) is not a function ; Zone: <root> ?

**Comment by princeraizadha** [comment]
Resolved .....
Issue Because of Old and new version i stuck same for FCM and geo Location ...... after 2 day struggle change the version from 5.0.0 to 4.18.0  and tham run npm i  in CMD  


![image](https://user-images.githubusercontent.com/4224441/52054723-6eb7e600-2583-11e9-93d1-c93488bae58f.png)
